---
parameters:
 age_groups:
  descr: age groups to divide population for contact structure
  value: ['0_18','18_40', '40_60', '60_']
 Cp:
  descr:   contact matrix for presymptomatic infectious individuals
  value: [[5.426261, 3.123604, 2.024298, 0.7721236],
            [2.243130, 6.950235, 3.665796, 1.0886557],
            [1.480757, 3.734041, 4.410192, 1.9935507],
            [0.723321, 1.420157, 2.553067, 3.1749014]] 
 Ca:
  descr:   contact matrix for asymptomatic infectious individuals
  value: [[5.426261, 3.123604, 2.024298, 0.7721236],
            [2.243130, 6.950235, 3.665796, 1.0886557],
            [1.480757, 3.734041, 4.410192, 1.9935507],
            [0.723321, 1.420157, 2.553067, 3.1749014]]
 Cs:
  descr:   contact matrix for symptomatic infectious individuals
  value: [[3.0936821, 2.0040047, 1.327612, 0.4982486], 
            [1.4391208, 3.7987661, 2.131639, 0.6528657], 
            [0.9711367, 2.1713234, 2.509774, 1.1321403], 
            [0.4667564, 0.8516666, 1.449890, 1.8562895]] 
 q:
  descr:   transmission probability (proportionality factor for q)
  value: 1
 n:
  descr:   proportion of diagnosed individuals that do not adhere to isolation meassures
  value: 0.05
 gamma:
  descr:   incubation rate
  value: 0.2
 delta1:
  descr:   recovery rate from asymptomatic infectious individuals
  value: 0.02
 delta2:
  descr:   recovery rate from symptomatic infectious individuals
  value: 0.03
 theta:
  descr:   rate from presymtomatic to a\symptomatic
  value: 0.2
 p:
  descr:   probability of being asymptimatic
  value: 0.3
 kappa:
  descr:   rate at which recovered become susceptible again
  value: 0.05
 tau_s:
  descr:   symptomatic diagnosing rate
  value: 0.05
 tau_r:
  descr:   random diagnosing rate
  value: 0.005
 tau_u:
  descr:   universal diagnosing rate
  value: 0.05
 tsp:
  descr:   tracing success probability
  value: 0.1
initial:
 S_0_18:
  descr: proportion of Suceptibles of 0-18
  value: 0.3
 S_18_40:
  descr: proportion of Suceptibles of 18-40
  value: 0.33
 S_40_60:
  descr: proportion of Suceptibles of 40-60
  value: 0.25
 S_60_:
  descr: proportion of Suceptibles of 60+
  value: 0.1
 Ipu_18_40: 
  descr: proportion of Infectius of 18-40
  value: 0.02
